### ISSUE TITLE
Update Documentation 

### ISSUE THREAD

**Issue by Shobuj-Paul** [IEEE-NITK/Anti-Anti-Masker#13]
- Documentation (README) needs to be updated
- More pictures and details regarding the ML model need to be added
- ROS documentation also requires much more detail about the environment and navigation
- Software versions and dependencies used must also be mentioned along with setting up the environment from scratch.

**Comment by Shobuj-Paul** [comment]
- Another thing to be added is environment setup for the simulation.

**Comment by Shobuj-Paul** [comment]
- In dependencies, Tensorflow, CUDA and OpenCV dependencies also need to be added.
- In cloning instructions change the `ssh` link to `https` link
- Few points regarding drone dynamics can be added
- Change the point regarding _aerodynamics_ under 3D model.

**Comment by Shivani-Chanda** [comment]
https://user-images.githubusercontent.com/93539029/157937210-b44bbade-e773-480f-82b6-0750ca808239.mp4

**Comment by Shobuj-Paul** [comment]
Put this video in the README, not here.
