### ISSUE TITLE
Improving Face Recognition Algorithm

### ISSUE THREAD

**Issue by Shobuj-Paul** [IEEE-NITK/Anti-Anti-Masker#7]
- The model is probably overfitted and does not well recognise non-surgical non-blue masks.
- Need to analyse the model and see if regularisation is possible.
- If not, we need to get a better dataset.
- Changing the model parameters could also be researched.

**Comment by bdiptesh99** [comment]
The new dataset has improved the performance considerably. The left-right bias has decreased but the model suffers when there is a non-white mask in the picture.
